### ISSUE TITLE
Verkar inte fungera

### ISSUE THREAD

**Issue by larsgon** [peterk/textamig#3]
Fick tips om att testa denna intressanta tjänst, men får det inte att fungera alls. Testade med ett Youtube-klipp i går kväll och ett nytt nu på morgonen, men har fortfarande inte fått något mejl tillbaka efter flera timmar.

**Comment by peterk** [comment]
Hej! Har du kollat i spam-korgen i ditt mailprogram? Jag ser att ett mail gått iväg till vad jag tror är din adress (slutar på skane.se). Annars, har du möjlighet att skicka mig länken till vilket videoklipp det gällde?

**Comment by larsgon** [comment]
Hej! Vad märkligt! Jag testade med min Gmail-adress i går, men Skåne-adressen idag. Hittar inget mejl i vare sig spam- eller någon annan inkorg. Jag tror att morgonens försök var med detta klipp: https://www.youtube.com/watch?v=1M3b7uvC_is (Jag tog mest ett i högen, som saknar all form av textning)
Tacksam för all hjälp, för detta vore verkligen spännande att testa!

**Comment by peterk** [comment]
Testkörde precis det klippet själv och det kom fram till min adress. Jag mailar undertexten till dig nu så ser vi om min forward fungerar i varjefall. Ska kika på mailinställningarna för att se om något kan förbättras på min sida.

**Comment by Tomand001** [comment]
Har skickat in ett par video, har fått en srt-fil men inte den andra, har testat med mail ...........@bollebygd.se och ........speedmail.se. Testade den jag fick, fick redigera lite men tyckte det var grymt bra, så tack för detta :)
P.S. Har kollat skräppost.

**Comment by peterk** [comment]
Tomand001 - ser att den video du angivit (med id som börjar på tVg76) inte finns öppet tillgänglig på Youtube. Kan den vara skyddad och bara synlig för ditt konto möjligen?

**Comment by Tomand001** [comment]
2018-05-01 16:08 skrev Peter Krantz:

> Tomand001 - ser att den video du angivit (med id som börjar på tVg76) inte finns öppet tillgänglig på Youtube. Kan den vara skyddad och bara synlig för ditt konto möjligen? 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

Har skickat igen, ang den förra filen så funkade inte min bollebygd.se
mail. 

Kan det vara nån inställning hos mig ? 

Links:
------
[1] https://github.com/peterk/textamig/issues/3#issuecomment-385679329
[2]

**Comment by peterk** [comment]
Jag har gjort en uppdatering för mailinställningarna som förhoppningsvis ska göra att mail kommer fram även genom nitiska mailfilter nu.

**Comment by jonassthlm** [comment]
hej Peter! 
kan du se nåt spår av en fil från mig? jag skickade in den imorse men ännu inget spår av någon text. och nej, inget mejl i skräpkorgen. 

J
