### ISSUE TITLE
Möjligt att addera Kaltura?

### ISSUE THREAD

**Issue by therealskoog** [peterk/textamig#6]
Får fått en kommentar/fråga på Youtube; om det går att göra tjänsten tillgänglig för Kaltura. Många svenska universitet och och högskolor använder Kaltura för att distribuera video och ljud. https://videos.kaltura.com

**Comment by peterk** [comment]
Det funkar eventuellt redan (minus en liten koll) men utmaningen är att få lärosäten publicerar sitt material utanför inloggning? Har du någon exempellänk?

**Comment by therealskoog** [comment]
Har bett om exempellänkar och påtalat att en förutsättning är att de ligger öppna. Har även noterat och du kör allt på engelska här, så jag rättar in mig i ledet nästa gång 😄

**Comment by lassman** [comment]
Hej, här är en exempellänk:
https://api.kaltura.nordu.net/index.php/extwidget/preview/partner_id/315/uiconf_id/23450068/entry_id/0_87rctte3/embed/dynamic
Samma video med kortlänk:
https://api.kaltura.nordu.net/tiny/kuq32

**Comment by lassman** [comment]
Får det här meddelandet när jag provar:
![skarmklipp](https://user-images.githubusercontent.com/45060184/48535914-2c003f00-e8ad-11e8-90ca-20f4667a2644.PNG)

**Comment by peterk** [comment]
Tror det är millimeter från att det ska lira (bara förvalideringen som inte släpper igenom). Ska försöka kika senare ikväll. Har alla lärosäten Sunets Kaltura-tjänst (dvs är alla länkar oavsett lärosäte på formen ...kaltura.nordu.net...) ?

**Comment by lassman** [comment]
Många lärosäten har det ca. 25.
Formen på URL:en borde vara densamma.
Får du det att lira vore det fantastiskt!

**Comment by peterk** [comment]
Tror det ska funka nu. Testa gärna.

**Comment by peterk** [comment]
Länkarna måste börja med https://api.kaltura.nordu.net

**Comment by peterk** [comment]
...och såklart vara publikt tillgängliga utan inloggningskrav.

**Comment by lassman** [comment]
Otroligt coolt! Får jag be de andra lärosätena att kolla om det fungerar
för dem också?

//Christer

Den tors 15 nov. 2018 kl 12:43 skrev Peter Krantz <notifications@github.com

**Comment by peterk** [comment]
Självklart! Tjänsten är ju uppe för alla. Förutsatt att man pratar svenska i videoklippen.

**Comment by lassman** [comment]
Jag måste ställa den självklara frågan, finns det någon motsvarande sajt
för engelska?
Kanske är ett förbättringsförslag?

//Christer

Den tors 15 nov. 2018 kl 13:12 skrev Peter Krantz <notifications@github.com

**Comment by peterk** [comment]
Från början var det inte tänkt så eftersom Youtube redan har realtidsstöd för transkribering till engelska. Jag skulle dock kunna kika på att lägga till det. Ingen stor grej.

**Comment by lassman** [comment]
Du är guld! Det kommer nog läggar upp en del Kalturalänkar framöver, hoppas
sajten pallar!

//Christer

Den tors 15 nov. 2018 kl 15:39 skrev Peter Krantz <notifications@github.com
